min_disparity: 20
num_disparities: 256
block_size: 15
p1: 600
p2: 2000
disp_12_max_diff: 10
pre_filter_cap: 4
uniqueness_ratio: 14
speckle_window_size: 1500
speckle_range: 2
mode: 3
apply_bilateral_filter: False
bilateral_filter_size: 21
bilateral_filter_sigma: 30
apply_wls_filter: False
wls_filter_sigma_color: 0.8
wls_filter_lambda: 100
