d415_min_disparity: 80
d415_num_disparities: 272
d415_block_size: 25
d415_p1: 1000
d415_p2: 4000
d435_min_disparity: 16
d435_num_disparities: 256
d435_block_size: 19
d435_p1: 1000
d435_p2: 4000
disp_12_max_diff: -1
pre_filter_cap: 1
uniqueness_ratio: 15
speckle_window_size: 2048
speckle_range: 1
mode: 3
apply_bilateral_filter: False
bilateral_filter_size: 3
bilateral_filter_sigma: 3
apply_wls_filter: False
wls_filter_sigma_color: 1.0
wls_filter_lambda: 20000
wls_filter_radius: 5
wls_filter_sigma_lrc_thresh: 24
use_median_filter: False
median_filter_size: 5
