min_disparity: 32
num_disparities: 256
block_size: 15
p1: 400
p2: 1600
disp_12_max_diff: -1
pre_filter_cap: 4
uniqueness_ratio: 1
speckle_window_size: 1
speckle_range: 1
mode: 3
apply_bilateral_filter: True
bilateral_filter_size: 3
bilateral_filter_sigma: 3
apply_wls_filter: False
wls_filter_sigma_color: 1.0
wls_filter_lambda: 20000
wls_filter_radius: 5
wls_filter_sigma_lrc_thresh: 24
use_median_filter: True
median_filter_size: 11
